apiVersion: v1
kind: Namespace
metadata:
  name: cloudsentinel
---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cloudsentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudsentinel-backend
  template:
    metadata:
      labels:
        app: cloudsentinel-backend
    spec:
      containers:
        - name: backend
          image: cloudsentinel-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: cloudsentinel
spec:
  selector:
    app: cloudsentinel-backend
  ports:
    - port: 5000
      targetPort: 5000
---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: cloudsentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudsentinel-frontend
  template:
    metadata:
      labels:
        app: cloudsentinel-frontend
    spec:
      containers:
        - name: frontend
          image: cloudsentinel-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7001
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: cloudsentinel
spec:
  type: NodePort
  selector:
    app: cloudsentinel-frontend
  ports:
    - port: 7001
      targetPort: 7001
      nodePort: 30001
